# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01cde055151956355a39c30c50aae51381466837c6d7588700db0800d3389e5a7e721023cd9cd0dc5a3b2875693035ed647aba9831ec25f90d26607bb0be4005

test:
  secret_key_base: fa448fc391d4c5d7579f1e49ccbceb9f050b8eee434538de0ba4bd7c9413b804a799f0bf71c14d31a5b73954fc7cbf221440e07f874b37023c5e038f740763d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
